const HTTP_UNAUTHORIZED = 401;
const HTTP_FORBIDDEN = 403;
export const HTTP_NOT_FOUND = 404;

export const TERMINAL_ACCESS_STATUSES = new Set([
  HTTP_UNAUTHORIZED,
  HTTP_FORBIDDEN,
  HTTP_NOT_FOUND,
]);
