/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as AppImport } from './routes/_app';
import { Route as AuthenticatedImport } from './routes/_authenticated';
import { Route as ForgotPasswordImport } from './routes/forgot-password';
import { Route as LoginImport } from './routes/login';
import { Route as RegisterImport } from './routes/register';
import { Route as ResetPasswordImport } from './routes/reset-password';
import { Route as VerifyEmailImport } from './routes/verify-email';
import { Route as STokenImport } from './routes/s.$token';
import { Route as AppIndexImport } from './routes/_app/index';
import { Route as AppDashboardImport } from './routes/_app/dashboard';
import { Route as AppOauthConsentImport } from './routes/_app/oauth.consent';
import { Route as AppNotesIndexImport } from './routes/_app/notes/index';
import { Route as AppNotesNoteIdImport } from './routes/_app/notes/$noteId';
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index';
import { Route as AuthenticatedNotesIndexImport } from './routes/_authenticated/notes/index';
import { Route as AuthenticatedNotesNoteIdImport } from './routes/_authenticated/notes/$noteId';

// Create Virtual Childrent

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any);

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any);

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any);

const VerifyEmailRoute = VerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRoute,
} as any);

const STokenRoute = STokenImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRoute,
} as any);

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any);

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any);

const AppOauthConsentRoute = AppOauthConsentImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => AppRoute,
} as any);

const AppNotesIndexRoute = AppNotesIndexImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AppRoute,
} as any);

const AppNotesNoteIdRoute = AppNotesNoteIdImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRoute,
} as any);

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedNotesIndexRoute = AuthenticatedNotesIndexImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedNotesNoteIdRoute = AuthenticatedNotesNoteIdImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AuthenticatedRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AppImport;
      parentRoute: typeof rootRoute;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthenticatedImport;
      parentRoute: typeof rootRoute;
    };
    '/forgot-password': {
      id: '/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof ForgotPasswordImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterImport;
      parentRoute: typeof rootRoute;
    };
    '/reset-password': {
      id: '/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof ResetPasswordImport;
      parentRoute: typeof rootRoute;
    };
    '/verify-email': {
      id: '/verify-email';
      path: '/verify-email';
      fullPath: '/verify-email';
      preLoaderRoute: typeof VerifyEmailImport;
      parentRoute: typeof rootRoute;
    };
    '/s/$token': {
      id: '/s/$token';
      path: '/s/$token';
      fullPath: '/s/$token';
      preLoaderRoute: typeof STokenImport;
      parentRoute: typeof rootRoute;
    };
    '/_app/': {
      id: '/_app/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AppIndexImport;
      parentRoute: typeof AppImport;
    };
    '/_app/dashboard': {
      id: '/_app/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AppDashboardImport;
      parentRoute: typeof AppImport;
    };
    '/_app/oauth/consent': {
      id: '/_app/oauth/consent';
      path: '/oauth/consent';
      fullPath: '/oauth/consent';
      preLoaderRoute: typeof AppOauthConsentImport;
      parentRoute: typeof AppImport;
    };
    '/_app/notes/': {
      id: '/_app/notes/';
      path: '/notes';
      fullPath: '/notes';
      preLoaderRoute: typeof AppNotesIndexImport;
      parentRoute: typeof AppImport;
    };
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId';
      path: '/notes/$noteId';
      fullPath: '/notes/$noteId';
      preLoaderRoute: typeof AppNotesNoteIdImport;
      parentRoute: typeof AppImport;
    };
    '/_authenticated/': {
      id: '/_authenticated/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/';
      path: '/notes';
      fullPath: '/notes';
      preLoaderRoute: typeof AuthenticatedNotesIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
    '/_authenticated/notes/$noteId': {
      id: '/_authenticated/notes/$noteId';
      path: '/notes/$noteId';
      fullPath: '/notes/$noteId';
      preLoaderRoute: typeof AuthenticatedNotesNoteIdImport;
      parentRoute: typeof AuthenticatedImport;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '': typeof AppRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/verify-email': typeof VerifyEmailRoute;
  '/s/$token': typeof STokenRoute;
  '/': typeof AppIndexRoute;
  '/dashboard': typeof AppDashboardRoute;
  '/oauth/consent': typeof AppOauthConsentRoute;
  '/notes': typeof AppNotesIndexRoute;
  '/notes/$noteId': typeof AppNotesNoteIdRoute;
}

export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/verify-email': typeof VerifyEmailRoute;
  '/s/$token': typeof STokenRoute;
  '/': typeof AppIndexRoute;
  '/dashboard': typeof AppDashboardRoute;
  '/oauth/consent': typeof AppOauthConsentRoute;
  '/notes': typeof AppNotesIndexRoute;
  '/notes/$noteId': typeof AppNotesNoteIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/_app': typeof AppRoute;
  '/_authenticated': typeof AuthenticatedRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/verify-email': typeof VerifyEmailRoute;
  '/s/$token': typeof STokenRoute;
  '/_app/': typeof AppIndexRoute;
  '/_app/dashboard': typeof AppDashboardRoute;
  '/_app/oauth/consent': typeof AppOauthConsentRoute;
  '/_app/notes/': typeof AppNotesIndexRoute;
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute;
  '/_authenticated/': typeof AuthenticatedIndexRoute;
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexRoute;
  '/_authenticated/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '' | '/forgot-password' | '/login' | '/register' | '/reset-password' | '/verify-email' | '/s/$token' | '/' | '/dashboard' | '/oauth/consent' | '/notes' | '/notes/$noteId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/forgot-password' | '/login' | '/register' | '/reset-password' | '/verify-email' | '/s/$token' | '/' | '/dashboard' | '/oauth/consent' | '/notes' | '/notes/$noteId';
  id: '__root__' | '/_app' | '/_authenticated' | '/forgot-password' | '/login' | '/register' | '/reset-password' | '/verify-email' | '/s/$token' | '/_app/' | '/_app/dashboard' | '/_app/oauth/consent' | '/_app/notes/' | '/_app/notes/$noteId' | '/_authenticated/' | '/_authenticated/notes/' | '/_authenticated/notes/$noteId';
  fileRoutesById: FileRoutesById;
}

export interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute;
  AppDashboardRoute: typeof AppDashboardRoute;
  AppOauthConsentRoute: typeof AppOauthConsentRoute;
  AppNotesIndexRoute: typeof AppNotesIndexRoute;
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppOauthConsentRoute: AppOauthConsentRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

export interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
  AuthenticatedNotesIndexRoute: typeof AuthenticatedNotesIndexRoute;
  AuthenticatedNotesNoteIdRoute: typeof AuthenticatedNotesNoteIdRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedNotesIndexRoute: AuthenticatedNotesIndexRoute,
  AuthenticatedNotesNoteIdRoute: AuthenticatedNotesNoteIdRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren);

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  VerifyEmailRoute: typeof VerifyEmailRoute;
  STokenRoute: typeof STokenRoute;
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  STokenRoute: STokenRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/_authenticated",
        "/forgot-password",
        "/login",
        "/register",
        "/reset-password",
        "/verify-email",
        "/s/$token"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/dashboard",
        "/_app/oauth/consent",
        "/_app/notes/",
        "/_app/notes/$noteId"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/",
        "/_authenticated/notes/",
        "/_authenticated/notes/$noteId"
      ]
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/verify-email": {
      "filePath": "verify-email.tsx"
    },
    "/s/$token": {
      "filePath": "s.$token.tsx"
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard": {
      "filePath": "_app/dashboard.tsx",
      "parent": "/_app"
    },
    "/_app/oauth/consent": {
      "filePath": "_app/oauth.consent.tsx",
      "parent": "/_app"
    },
    "/_app/notes/": {
      "filePath": "_app/notes/index.tsx",
      "parent": "/_app"
    },
    "/_app/notes/$noteId": {
      "filePath": "_app/notes/$noteId.tsx",
      "parent": "/_app"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/notes/": {
      "filePath": "_authenticated/notes/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/notes/$noteId": {
      "filePath": "_authenticated/notes/$noteId.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
