/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as AuthenticatedImport } from './routes/_authenticated';
import { Route as LoginImport } from './routes/login';
import { Route as RegisterImport } from './routes/register';
import { Route as STokenImport } from './routes/s.$token';
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index';
import { Route as AuthenticatedNotesNoteIdImport } from './routes/_authenticated/notes.$noteId';

// Create Virtual Childrent

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any);

const STokenRoute = STokenImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedNotesNoteIdRoute = AuthenticatedNotesNoteIdImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AuthenticatedRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthenticatedImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterImport;
      parentRoute: typeof rootRoute;
    };
    '/s/$token': {
      id: '/s/$token';
      path: '/s/$token';
      fullPath: '/s/$token';
      preLoaderRoute: typeof STokenImport;
      parentRoute: typeof rootRoute;
    };
    '/_authenticated/': {
      id: '/_authenticated/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
    '/_authenticated/notes/$noteId': {
      id: '/_authenticated/notes/$noteId';
      path: '/notes/$noteId';
      fullPath: '/notes/$noteId';
      preLoaderRoute: typeof AuthenticatedNotesNoteIdImport;
      parentRoute: typeof AuthenticatedImport;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/s/$token': typeof STokenRoute;
  '/': typeof AuthenticatedIndexRoute;
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute;
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/s/$token': typeof STokenRoute;
  '/': typeof AuthenticatedIndexRoute;
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/_authenticated': typeof AuthenticatedRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/s/$token': typeof STokenRoute;
  '/_authenticated/': typeof AuthenticatedIndexRoute;
  '/_authenticated/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '' | '/login' | '/register' | '/s/$token' | '/' | '/notes/$noteId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/login' | '/register' | '/s/$token' | '/' | '/notes/$noteId';
  id: '__root__' | '/_authenticated' | '/login' | '/register' | '/s/$token' | '/_authenticated/' | '/_authenticated/notes/$noteId';
  fileRoutesById: FileRoutesById;
}

export interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
  AuthenticatedNotesNoteIdRoute: typeof AuthenticatedNotesNoteIdRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedNotesNoteIdRoute: AuthenticatedNotesNoteIdRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren);

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  STokenRoute: typeof STokenRoute;
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  STokenRoute: STokenRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/login",
        "/register",
        "/s/$token"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/",
        "/_authenticated/notes/$noteId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/s/$token": {
      "filePath": "s.$token.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/notes/$noteId": {
      "filePath": "_authenticated/notes.$noteId.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
