export { COPILOT_CONVERSATION_STORAGE_KEY } from './copilot-storage';
export { formatRelativeTime } from './format-relative-time';
export { formatShortcut } from './format-shortcut';
export { generateId } from './generateId';
export { getInitials } from './get-initials';
export { DEFAULT_LOCALE, I18N_STORAGE_KEY, SUPPORTED_LOCALES } from './locale';
export type { SupportedLocale } from './locale';
export { logger } from './logger';
export { IMAGE_MIME_TYPES, MAX_IMAGE_BYTES } from './note-image';
export type { ImageMimeType } from './note-image';
export { pickDefined } from './pick-defined';
export { isMacPlatform } from './platform';
export { safeLocalStorage, safeSessionStorage } from './safe-storage';
export { isStoredImageUrl, STORED_IMAGE_HOST } from './stored-image-url';
