import type { IndexedModel, ModelCatalog } from '@knowtis/ai-gateway';

import { unservedFloorModels } from '../modules/ai/domain/model-catalog/floor-models';
import type { ModelsDevCatalog } from '../modules/ai/domain/ports/models-dev.port';
import type { UpstreamCatalog } from '../modules/ai/domain/ports/openrouter-models.port';

export const SNAPSHOT_HEADER =
  '// Generated by apps/api/src/scripts/refresh-model-index-snapshot.ts from models.dev and OpenRouter /api/v1/models.';

/**
 * Why these reads must not become the snapshot; empty when they may. A partial
 * read, or one that cannot support and fully price every floor model, would
 * ship a floor that records `costUsd=0` for the platform's own spend.
 */
export function snapshotRefusals(
  modelsDev: ModelsDevCatalog,
  openRouter: UpstreamCatalog,
  catalog: ModelCatalog
): string[] {
  const refusals: string[] = [];
  if (modelsDev.discarded.length > 0) {
    refusals.push(
      `models.dev discarded ${modelsDev.discarded.length} entries: ${modelsDev.discarded.join(', ')}`
    );
  }
  if (!openRouter.complete) {
    refusals.push('OpenRouter pagination stopped before the last page');
  }
  const unserved = unservedFloorModels(catalog);
  if (unserved.length > 0) {
    refusals.push(
      `unsupported, unpriced or without an input window: ${unserved.join(', ')}`
    );
  }
  return refusals;
}

function byId(a: IndexedModel, b: IndexedModel): number {
  if (a.id === b.id) {
    return 0;
  }
  return a.id < b.id ? -1 : 1;
}

/** The snapshot module source: one JSON row per line, sorted by id. */
export function renderModelIndexSnapshot(
  rows: readonly IndexedModel[]
): string {
  const body = [...rows]
    .sort(byId)
    .map((row) => `  ${JSON.stringify(row)},`)
    .join('\n');
  return [
    SNAPSHOT_HEADER,
    "import type { IndexedModel } from './indexed-model';",
    '',
    'export const MODEL_INDEX_SNAPSHOT: readonly IndexedModel[] = [',
    body,
    '];',
    '',
  ].join('\n');
}
