import { resolve } from 'node:path';

import type { IndexedModel, ModelIndexCatalog } from '@knowtis/ai-gateway';

import { unservedFloorModels } from '../modules/ai/domain/model-catalog/floor-models';
import type { ModelsDevCatalog } from '../modules/ai/domain/ports/models-dev.port';
import type { UpstreamCatalog } from '../modules/ai/domain/ports/openrouter-models.port';
import { isoDateOf } from '../modules/ai/domain/value-objects/utc-day';

export const SNAPSHOT_HEADER =
  '// Generated by apps/api/src/scripts/refresh-model-index-snapshot.ts from models.dev and OpenRouter /api/v1/models.';

/** The vendored snapshot module the refresh script rewrites. */
export const SNAPSHOT_PATH = resolve(
  __dirname,
  '../../../../packages/ai-gateway/src/catalog/model-index.snapshot.ts'
);

/**
 * Why these reads must not become the snapshot; empty when they may. A partial
 * read, or one that leaves a platform or BYOK intent route resolving to no
 * supported, fully priced row with an input window, would ship a floor with no
 * served model for that intent.
 */
export function snapshotRefusals(
  modelsDev: ModelsDevCatalog,
  openRouter: UpstreamCatalog,
  catalog: ModelIndexCatalog
): string[] {
  const refusals: string[] = [];
  if (modelsDev.discarded.length > 0) {
    refusals.push(
      `models.dev discarded ${modelsDev.discarded.length} entries: ${modelsDev.discarded.join(', ')}`
    );
  }
  if (!openRouter.complete) {
    refusals.push('OpenRouter pagination stopped before the last page');
  }
  const unserved = unservedFloorModels(catalog);
  if (unserved.length > 0) {
    refusals.push(
      `unsupported, unpriced, without an input window or unrouted: ${unserved.join(', ')}`
    );
  }
  return refusals;
}

function byId(a: IndexedModel, b: IndexedModel): number {
  if (a.id === b.id) {
    return 0;
  }
  return a.id < b.id ? -1 : 1;
}

/** The snapshot module source: the UTC day of `generatedAt`, then one JSON row per line, sorted by id. */
export function renderModelIndexSnapshot(
  rows: readonly IndexedModel[],
  generatedAt: Date
): string {
  const body = [...rows]
    .sort(byId)
    .map((row) => `  ${JSON.stringify(row)},`)
    .join('\n');
  return [
    SNAPSHOT_HEADER,
    "import type { IndexedModel } from './indexed-model';",
    '',
    '/** The UTC day the snapshot was generated, `YYYY-MM-DD`. */',
    `export const MODEL_INDEX_SNAPSHOT_DATE = '${isoDateOf(generatedAt)}';`,
    '',
    'export const MODEL_INDEX_SNAPSHOT: readonly IndexedModel[] = [',
    body,
    '];',
    '',
  ].join('\n');
}
